name: ipd_getx_project_backup
version: 1.0.0+1
publish_to: none
description: A new Flutter application.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  avatar_glow: 2.0.2
  font_awesome_flutter: ^9.2.0
  intl: 0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  get_cli: ^1.6.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

